# Use "Update data cache" pipeline from cctbx_project
resources:
  repositories:
    - repository: cctbx_project
      type: github
      name: cctbx/cctbx_project
      endpoint: phenix-installer

jobs:
- template: .azure-pipelines/azure-pipelines-data-cache.yml@cctbx_project
