# Pipeline name: Update data cache

# Daily update of data cache artifacts
#   - miniconda
#   - chem_data
#   - phenix_regression
#   - phenix_examples

# no continuous integration or pull request builds
trigger: none
pr: none

# Daily updates
schedules:
- cron: '0 5 * * *'
  displayName: Daily update of data cache artifacts
  branches:
    include:
    - master
    - main
  always: true

# template location
resources:
  repositories:
    - repository: cctbx_project
      type: github
      name: cctbx/cctbx_project
      endpoint: phenix-installer
  # this pipeline resource needs to be commented out when run for the first time
  pipelines:
  - pipeline: data_cache
    source: 'Update data cache'

extends:
  template: .azure-pipelines/templates/update-data-cache.yml@cctbx_project
